### ISSUE TITLE
Naming of the module

### ISSUE THREAD

**Issue by csshugs** [alienlebarge/inuit-flexbox#13]
Why not naming the classes `.layout` and `.layout__item`?

In my opinion it doesn't matter for the naming which technique is being used to obtain the grid-behaviour. The inuit [layout](https://github.com/inuitcss/objects.layout) classes aren't named `.inline-block` after all (because `display: inline-block` is being used to get the styling right), but are named for the job they are doing, which is: layout.

I imagine in the future, when flexbox is finally standard, it would look weird to name something like the classes for a global grid-system after a CSS declaration.

**Comment by alienlebarge** [comment]
Initially, the aim of this project was to test FlexBox. I kept the name from there.
But I think you're right. Use names like `.layout` is more appropriate.

I will change that.
